### ISSUE TITLE
Where can I get the "Random" results shown in the readme？

### ISSUE THREAD

**Issue by SunJiaJ** [Ericonaldo/ILSwiss#18]
- Random表格中展示的结果是用类似随机游走（没用强化学习算法）的方法得到的结果嘛？我没有在exp_specs中找到对应的yaml文件。
- 有没有在这个代码框架下的论文发表呢？我想参考一下。

**Comment by Ericonaldo** [comment]
1. Random就是不用训练策略的初始化网络直接跑出来的分数
2. 我们在这个框架下发表了一些论文，例如[COIL](https://github.com/apexrl/COIL), [DePO](https://github.com/apexrl/DePO), [EBIL](https://github.com/apexrl/EBIL-torch)（老版本的ILSwiss，很多不一致的地方）等。此外，正如README所说的，这份代码基于rlswiss和rlkit，所以基于这两套代码的论文的code风格也有很多兼容的部分。
