### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by lzl60109** [Ericonaldo/ILSwiss#19]
Traceback (most recent call last):
  File "run_scripts/gen_expert_demos.py", line 335, in <module>
    experiment(exp_specs)
  File "run_scripts/gen_expert_demos.py", line 152, in experiment
    policy = joblib.load(specs["expert_path"])["policy"]
  File "/mnt/liang/miniconda3/envs/py38/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './logs/test-gen-hopper-demos/test_gen_hopper_demos_2023_04_13_09_54_46_0000--s-0/params.pkl'

Excuse me, where is this params.pkl file?

**Comment by Ericonaldo** [comment]
Please train your own hopper policy model with our provided scripts and replace the `expert_path` as the path of your own policy model.

**Comment by lzl60109** [comment]
The above error came after I ran this scripts :

**python run_experiment -e \exp_specs\gen_expert\hopper.yaml -g 0**

So which script you provided can I use to train my own hopper policy?

**Comment by Ericonaldo** [comment]
Check the readme. https://github.com/Ericonaldo/ILSwiss#running-rl-algorithms

**Comment by lzl60109** [comment]
### RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Can I use the CPU to run the code, because there is no GPU on VMWare

**Comment by Ericonaldo** [comment]
https://github.com/Ericonaldo/ILSwiss/blob/main/exp_specs/sac/sac_hopper.yaml#L6
Change this term into False (similar for all other scripts)

**Comment by lzl60109** [comment]
Thanks, I just saw this property
