### ISSUE TITLE
想问下AIRL能否用于TD3或者ddpg?

### ISSUE THREAD

**Issue by HsingWaves** [Ericonaldo/ILSwiss#9]
作者你们好，
我看AIRL原文中，AIRL用于on-policy algorithm. 如果我想用AIRL作用于ddpg，但ddpg model只输出一个确定的动作，AIRL该如何训练？ 

谢谢！

**Comment by Ericonaldo** [comment]
可以，SAC, DDPG都可以。和确定不确定没关系。AIRL / GAIL 只是提供了一种reward。
